### ISSUE TITLE
Crash when breaking an Item Interface Pipe

### ISSUE THREAD

**Issue by zacklmoore** [TeamBR-Modding/NeoTech#134]
Hello, crash report here. I broke an item interface pipe that had a motherboard with the 8 hard drive upgrades as items were flowing through it and had this crash (latest version):

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LLibrary (llibrary-0.8.1-1.8.9.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.8.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2/17/16 11:52 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.onPipeEntered(ResourceEntity.java:194)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.travelPath(ResourceEntity.java:166)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.updateEntity(ResourceEntity.java:106)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:130)
    at com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe.onServerTick(ItemInterfacePipe.scala:339)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe.func_73660_a(ItemInterfacePipe.scala:28)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.onPipeEntered(ResourceEntity.java:194)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.travelPath(ResourceEntity.java:166)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.updateEntity(ResourceEntity.java:106)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:130)
    at com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe.onServerTick(ItemInterfacePipe.scala:339)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe.func_73660_a(ItemInterfacePipe.scala:28)

-- Block entity being ticked --
Details:
    Name: pipeItemBasicInterface // com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe
    Block type: ID #796 (tile.neotech:pipeItemBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (457,79,23), Chunk: (at 9,4,7 in 28,1; contains blocks 448,0,16 to 463,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #796 (tile.neotech:pipeItemBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['tofugames'/1490, l='New World', x=449.80, y=79.00, z=22.57]]
    Chunk stats: ServerChunkCache: 605 Drop: 0
    Level seed: 8737770794538217775
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 36.00,64.00,220.00 - World: (36,64,220), Chunk: (at 4,4,12 in 2,13; contains blocks 32,0,208 to 47,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 36166 game time, 11671 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 56999 (now: false), thunder time: 26825 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 678203272 bytes (646 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP 9.19 Powered by Forge 11.15.1.1747 Optifine OptiFine_1.8.9_HD_U_H2 79 mods loaded, 79 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1747.jar) 
    UCHIJAAAA   Forge{11.15.1.1747} [Minecraft Forge] (forge-1.8.9-11.15.1.1747.jar) 
    UCHIJAAAA   securitycraft{v1.8.1} [SecurityCraft] ([1.8.8] SecurityCraft v1.8.1.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
    UCHIJAAAA   AutoSapling{1.0} [Auto Sapling] (AutoSapling 1.2 MC1.8.9.jar) 
    UCHIJAAAA   bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1896-universal.jar) 
    UCHIJAAAA   JEI{2.26.0.154} [Just Enough Items] (jei_1.8.9-2.26.0.154.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-17} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-17.jar) 
    UCHIJAAAA   bookshelfapi{2.3.1} [Bookshelf] (Bookshelf-1.8.9-2.3.1.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-pre12} [BuildCraft] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-pre12} [BC Transport] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-pre12} [BC Builders] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.2.0-pre12-compat1} [BuildCraft Compat] (buildcraft-7.2.0-pre12-compat1.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-pre12} [BC Energy] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-pre12} [BC Factory] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre12} [BC Silicon] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre12} [BC Robotics] (buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
    UCHIJAAAA   cosmeticarmorreworked{1.8.9-v1b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v1b.jar) 
    UCHIJAAAA   craftingtweaks{3.0.41} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.41.jar) 
    UCHIJAAAA   CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
    UCHIJAAAA   lootablebodies{1.4.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.0.jar) 
    UCHIJAAAA   cyclopscore{0.5.0} [Cyclops Core] (CyclopsCore-1.8.9-0.5.0.jar) 
    UCHIJAAAA   spawn_defuzzer{1.1.0} [Spawn Defuzzer] (defuzz-1.2.0.jar) 
    UCHIJAAAA   dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar) 
    UCHIJAAAA   ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.4.jar) 
    UCHIJAAAA   FFS{1.8.9-1.4.5.7.91} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.4.5.7.91.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
    UCHIJAAAA   fluidconverters{2.0.0} [FluidConverters] (FluidConverters-1.8.9-2.0.0.jar) 
    UCHIJAAAA   substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAA   foundry{1.4.0.0} [Foundry] (Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAA   HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
    UCHIJAAAA   hgp{Release} [Horizontal Glass Panes] (hgp-1.8.9-1.0.2.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons] (JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.14} [K4Lib] (k4lib-1.8.9-1.0.14-universal.jar) 
    UCHIJAAAA   llibrary{0.8.1} [LLibrary] (llibrary-0.8.1-1.8.9.jar) 
    UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   mcmultipart{1.0.6} [MCMultiPart] (MCMultiPart-1.0.6-universal.jar) 
    UCHIJAAAA   MC{4.5} [MedicineCraft] (MedicineCraft V5.3 1.8.9.jar) 
    UCHIJAAAA   MineMenu{1.3.0} [MineMenu] (MineMenu-1.8.9-1.3.0.B45-universal.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   moarsigns{2.0.1} [MoarSigns] (MoarSigns-1.8.9-2.0.1.jar) 
    UCHIJAAAA   ModNameTooltip{1.0.0} [Mod Name Tooltip] (modnametooltip_1.8.8-1.0.0.jar) 
    UCHIJAAAA   moreplayermodels{1.8.8} [MorePlayerModels] (MorePlayerModels_1.8.8.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar) 
    UCHIJAAAA   neotech{2.3.5} [NeoTech] (NeoTech-1.8.9-2.3.5.jar) 
    UCHIJAAAA   recipehandler{0.3} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.8.X).jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   simplerecipes{1.8.9a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.8.9a.jar) 
    UCHIJAAAA   parachutemod{1.2.2} [Parachute Mod] (parachutemod-ng-1.8.9-1.2.2-341.jar) 
    UCHIJAAAA   PassthroughSigns{1.0.2} [Passthrough Signs] (PassthroughSigns-1.8.X-1.0.2.B4.jar) 
    UCHIJAAAA   progressiveautomation{1.6.34} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.34.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAA   RandomThings{3.6.2} [Random Things] (RandomThings-MC1.8.9-3.6.2.jar) 
    UCHIJAAAA   reborncore{1.4.3.20} [RebornCore] (RebornCore-1.8.9-1.4.3.20-universal.jar) 
    UCHIJAAAA   RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAAAA   rftools{4.22beta18} [RFTools] (rftools-1.8.9-4.22beta18.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.8.8.jar) 
    UCHIJAAAA   ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
    UCHIJAAAA   SimpleDimensions{1.2} [Simple Dimensions] (SimpleDimensions-1.2.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.0} [Storage Drawers] (StorageDrawers-1.8.9-2.4.0.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   thaumicinfusion{4.8} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.8.jar) 
    UCHIJAAAA   thutcore{2.2.2} [ThutCore] (thutcore-2.2.2.jar) 
    Loaded coremods (and transformers): 
LLibrary (llibrary-0.8.1-1.8.9.jar)
  net.ilexiconn.llibrary.common.asm.ClassHeirachyManager
  net.ilexiconn.llibrary.common.asm.HookPatchManager
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.8.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['tofugames'/1490, l='New World', x=449.80, y=79.00, z=22.57]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by pauljoda** [comment]
Is it the latest beta on curse or the latest release?  This is fixed in that beta so I'm closing this for now. If it crashes after updating post here again and I'll reopen it
