### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mario-88ce** [TeamBR-Modding/NeoTech#186]
What Version of NeoTech are you using: 2.3.9

If possible, did you break and replace the block: yes

Please Pastebin.com the crash Report and put link here:

thermal binder more will not work in survival mode it in creative mode , I also created a new world updated bookshelf api and even forge I tried to forge the .61 to .64 the machine still does not work with the new version of the mod

**Comment by pauljoda** [comment]
Did you give it molten tin? There is a new requirement of molten tin in the binding process. That is why a tank is there on the right and the description tab says you need molten tin

**Comment by mario-88ce** [comment]
No, now I have seen that there is the pond , but as it creates and inserts ? I can not, I can not find the method ...

**Comment by pauljoda** [comment]
Melt some tin in the crucible and pipe it in

**Comment by mario-88ce** [comment]
in the crucible makes me just insert the original minecraft materials on the tin I do not insert ago , the crucible is empty when I try to enter the tin

**Comment by mario-88ce** [comment]
I tried to insert all kinds of tin in the crucible from the block to the powder I do not put anyone does just makes me melt the iron and gold , I also tried a different version of the forge but nothing .

**Comment by pauljoda** [comment]
Try deleting your config directory and letting the file regenerate

**Comment by mario-88ce** [comment]
done nothing I also created a new world , do not go no place in the crucible makes me none of the mod including tin materials

**Comment by pauljoda** [comment]
Can you post some screenshots of you trying so I can make sure everything is setup correctly?

**Comment by mario-88ce** [comment]
http://i65.tinypic.com/23wk2kl.png

## Image 1 creative mode, Creative Rf storage near Electric Crucible.

http://i65.tinypic.com/o5t2k0.png
http://i68.tinypic.com/2rw4whz.png

## Images 2 and 3, Tin ingot and Iron ingot.

http://i68.tinypic.com/b9hwet.png

## Image 4 empy crucible.

http://i67.tinypic.com/2crv8n4.png

## Image 5 I try to put the tin ingot in the crucible but not located.

http://i67.tinypic.com/14mqfyw.png

## Image 6 Iron Ingot instead is inserted and melts.

I also created a test version of minecraft clean from all other mod and I've run only Neotech and Bookshelf Bees with the 'latest version of Forge in order to avoid any conflicts, nothing does not make me put the tin and other minerals themselves the mod.

**Comment by pauljoda** [comment]
And you say you can't even put it into the slot?

**Comment by mario-88ce** [comment]
no I did not make it his own post the only materials that can be entered are iron and 'gold then I have not tried the other original materials minecraft but I tried all those of mod and no one can insert into the slot, even in other forms as in powder or chips.

**Comment by pauljoda** [comment]
This is a very odd bug I can't seem to replicate so sorry if I'm asking alot. I want to make sure we figure this out. Can you create a pastebin at pastebin.com of the contents of the crucibleRecipes.json file located in the config directory so I can make sure that is loading correctly?

**Comment by mario-88ce** [comment]
http://pastebin.com/QtaSfkn2

**Comment by pauljoda** [comment]
Have you changed this file at all? Try deleting it and seeing if the regenerated one works. This file is missing a large amount of recipes

**Comment by mario-88ce** [comment]
This is the newly regenerated files from the clean version of minecraft ie the one with only the mod and the 'Api so do not know how to do already have canceled two times the configuration folder and downloaded once the mod

**Comment by pauljoda** [comment]
Try changing the contents of that file to this, this is what the registry should generate  http://pastebin.com/ghgCD08z

**Comment by mario-88ce** [comment]
excuse me if I ask you are not very practical is the first time I do, with what I have to open that file to insert ourselves what?

**Comment by pauljoda** [comment]
That pastebin is what my mod generated for me. I loaded up a world with just it and Bookshelf and that is the file created. I'm saying try changing yours to match that since there seems to be an issue with the generation of yours. If that solves it I know to look at the generation of files. Another thing that may help me is the console output log, it should be labeled fmllatest somewhere in your instance folder

**Comment by mario-88ce** [comment]
you wanted to know, however, how to enter your code in my file, that is, as I open my file with that program?

Log: [17:24:27] [Client thread/INFO]: Setting user: Mario
[17:24:35] [Client thread/INFO]: LWJGL Version: 2.9.4
[17:24:46] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:NeoTech
[17:24:51] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:24:52] [Thread-9/INFO]: Initializing LWJGL OpenAL
[17:24:52] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:24:52] [Thread-9/INFO]: OpenAL initialized.
[17:24:52] [Sound Library Loader/INFO]: Sound engine started
[17:25:00] [Client thread/INFO]: Created: 16x16 textures-atlas
[17:25:04] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Bookshelf, FMLFileResourcePack:NeoTech
[17:25:04] [Client thread/INFO]: SoundSystem shutting down...
[17:25:05] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[17:25:05] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:25:05] [Thread-11/INFO]: Initializing LWJGL OpenAL
[17:25:05] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:25:05] [Thread-11/INFO]: OpenAL initialized.
[17:25:05] [Sound Library Loader/INFO]: Sound engine started
[17:25:11] [Client thread/INFO]: Created: 512x512 textures-atlas
[17:25:15] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:25:23] [Server thread/INFO]: Starting integrated minecraft server version 1.8.9
[17:25:23] [Server thread/INFO]: Generating keypair
[17:25:24] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:25:24] [Server thread/INFO]: Preparing start region for level 0
[17:25:25] [Server thread/INFO]: Preparing spawn area: 2%
[17:25:26] [Server thread/INFO]: Preparing spawn area: 32%
[17:25:27] [Server thread/INFO]: Preparing spawn area: 87%
[17:25:28] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:25:28] [Server thread/INFO]: Changing view distance to 12, from 10
[17:25:30] [Server thread/INFO]: Mario[local:E:b7a6bf7b] logged in with entity id 174 at (507.0979395704221, 158.3008329559356, 16.058471915428164)
[17:25:30] [Server thread/INFO]: Mario è entrato nel gioco
[17:25:33] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3124ms behind, skipping 62 tick(s)
[17:25:33] [Server thread/INFO]: Saving and pausing game...
[17:25:33] [Server thread/INFO]: Saving chunks for level 'Prova'/Overworld
[17:25:33] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@277d1cdd[id=1cc47761-6bb1-32e8-bec7-285bfbf8c34b,name=Mario,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:59) [YggdrasilMinecraftSessionService$1.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:56) [YggdrasilMinecraftSessionService$1.class:?]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:165) [YggdrasilMinecraftSessionService.class:?]
    at net.minecraft.client.Minecraft.func_181037_M(Minecraft.java:2778) [ave.class:?]
    at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [bnp$3.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[17:25:34] [Server thread/INFO]: Saving chunks for level 'Prova'/Nether
[17:25:34] [Server thread/INFO]: Saving chunks for level 'Prova'/The End

**Comment by pauljoda** [comment]
This log doesn't seem to have anything I can use. To change your file, open it as you did before to pastebin it, even using notepad is fine, delete all that is there and copy and paste the code from the pastebin I posted into that document and save it

**Comment by mario-88ce** [comment]
I copied and pasted the code into the cruciblerecipes.json files after deleting the old code I saved and started minecraft but the problem remains the same materials do not fit ...

**Comment by pauljoda** [comment]
I have no idea what is causing this issue but I can't seem to replicate it. I really don't know what to tell you at this point. I'll keep an eye on it and see if I can find potential load issues but I'm just not seeing it

**Comment by mario-88ce** [comment]
sin liked this mod and my world is decree on it now to play I have to put a previous version otherwise I can no longer use the world :(

**Comment by mario-88ce** [comment]
It could be the jav version? because since a mod me wondering I am using the 'latest version, but 64-bit instead of 32 

anyway I downloaded the mod again and the 'Api from here: Http://teambrmodding.com:8080/
and this time I crashed, the crash log is this:

--- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 01/03/16 18.07
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/dyonovan/neotech/pipes/blocks/BlockPipeSpecial
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/dyonovan/neotech/pipes/blocks/BlockPipeSpecial
    at com.dyonovan.neotech.NeoTech$.<init>(NeoTech.scala:56)
    at com.dyonovan.neotech.NeoTech$.<clinit>(NeoTech.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraftforge.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:21)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:534)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: mcmultipart/block/BlockCoverable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: mcmultipart.block.BlockCoverable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1430191464 bytes (1363 MB) / 1912602624 bytes (1824 MB) up to 5156896768 bytes (4918 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2020m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UC  Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UC  bookshelfapi{2.3.4} [Bookshelf](Bookshelf-API-1.8.9-2.3.4-B8.jar) 
    UE  neotech{2.3.9} [NeoTech](NeoTech-1.8.9-2.3.9-B40.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 354.35' Renderer: 'GeForce GT 740M/PCIe/SSE2'

**Comment by pauljoda** [comment]
I am not sure what is going on here. Could be a bad forge installation

**Comment by mario-88ce** [comment]
I do not know why if I download the mod from here: http://mods.curse.com/mc-mods/minecraft/228643-neotech
The game starts with no problems and no crashes
if instead the discharge from here: Http://teambrmodding.com:8080/
the game does not start and crashes.

---

I wanted to ask one other thing the centrifuge is used to separate two fluids from one? If you because if I try to send gold or liquid iron in the centrifuge the game crashes?

report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 01/03/16 19.06
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.dyonovan.neotech.registries.CentrifugeRecipe.isValidInput(CentrifugeRecipeHandler.scala:141)
    at com.dyonovan.neotech.registries.CentrifugeRecipe.isValidInput(CentrifugeRecipeHandler.scala:116)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler$$anonfun$isValidInput$1.apply(AbstractRecipeHandler.scala:168)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler$$anonfun$isValidInput$1.apply(AbstractRecipeHandler.scala:166)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler.isValidInput(AbstractRecipeHandler.scala:166)
    at com.dyonovan.neotech.common.tiles.machines.processors.TileCentrifuge.canFill(TileCentrifuge.scala:188)
    at com.teambr.bookshelf.common.tiles.traits.FluidHandler$class.fill(FluidHandler.scala:73)
    at com.dyonovan.neotech.common.tiles.machines.processors.TileCentrifuge.fill(TileCentrifuge.scala:27)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$willAcceptResource$1.apply(FluidInterfacePipe.scala:196)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$willAcceptResource$1.apply(FluidInterfacePipe.scala:191)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.willAcceptResource(FluidInterfacePipe.scala:191)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$$anonfun$extractResourceOnShortestPath$2.apply$mcVI$sp(InterfacePipe.scala:249)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.extractResourceOnShortestPath(InterfacePipe.scala:245)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.extractResourceOnShortestPath(FluidInterfacePipe.scala:23)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.extractOnMode(InterfacePipe.scala:110)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.extractOnMode(FluidInterfacePipe.scala:23)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:111)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:105)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.tryExtractResources(FluidInterfacePipe.scala:105)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.doExtraction(FluidInterfacePipe.scala:96)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:144)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.onServerTick(FluidInterfacePipe.scala:312)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.func_73660_a(FluidInterfacePipe.scala:23)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.dyonovan.neotech.registries.CentrifugeRecipe.isValidInput(CentrifugeRecipeHandler.scala:141)
    at com.dyonovan.neotech.registries.CentrifugeRecipe.isValidInput(CentrifugeRecipeHandler.scala:116)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler$$anonfun$isValidInput$1.apply(AbstractRecipeHandler.scala:168)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler$$anonfun$isValidInput$1.apply(AbstractRecipeHandler.scala:166)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.registries.AbstractRecipeHandler.isValidInput(AbstractRecipeHandler.scala:166)
    at com.dyonovan.neotech.common.tiles.machines.processors.TileCentrifuge.canFill(TileCentrifuge.scala:188)
    at com.teambr.bookshelf.common.tiles.traits.FluidHandler$class.fill(FluidHandler.scala:73)
    at com.dyonovan.neotech.common.tiles.machines.processors.TileCentrifuge.fill(TileCentrifuge.scala:27)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$willAcceptResource$1.apply(FluidInterfacePipe.scala:196)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$willAcceptResource$1.apply(FluidInterfacePipe.scala:191)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.willAcceptResource(FluidInterfacePipe.scala:191)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$$anonfun$extractResourceOnShortestPath$2.apply$mcVI$sp(InterfacePipe.scala:249)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.extractResourceOnShortestPath(InterfacePipe.scala:245)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.extractResourceOnShortestPath(FluidInterfacePipe.scala:23)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.extractOnMode(InterfacePipe.scala:110)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.extractOnMode(FluidInterfacePipe.scala:23)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:111)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe$$anonfun$tryExtractResources$1.apply(FluidInterfacePipe.scala:105)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.tryExtractResources(FluidInterfacePipe.scala:105)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.doExtraction(FluidInterfacePipe.scala:96)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:144)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.onServerTick(FluidInterfacePipe.scala:312)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:88)
    at com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe.func_73660_a(FluidInterfacePipe.scala:23)

-- Block entity being ticked --
Details:
    Name: pipeFluidBasicInterface // com.dyonovan.neotech.pipes.tiles.fluid.FluidInterfacePipe
    Block type: ID #217 (tile.neotech:pipeFluidBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (509,88,15), Chunk: (at 13,5,15 in 31,0; contains blocks 496,0,0 to 511,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #217 (tile.neotech:pipeFluidBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: Prova
    All players: 1 total; [EntityPlayerMP['Mario'/173, l='Prova', x=507,82, y=88,00, z=13,88]]
    Chunk stats: ServerChunkCache: 948 Drop: 0
    Level seed: -4807616480202897380
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 112,00,64,00,252,00 - World: (112,64,252), Chunk: (at 0,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 38764 game time, 3494 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 119535 (now: false), thunder time: 39973 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_73, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 898986648 bytes (857 MB) / 2568495104 bytes (2449 MB) up to 5156896768 bytes (4918 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2020m
    IntCache: cache: 0, tcache: 54, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   bookshelfapi{2.3.4} [Bookshelf](Bookshelf-API-1.8.9-2.3.4-B8.jar) 
    UCHIJAAAA   neotech{2.3.9} [NeoTech](NeoTech-1.8.9-2.3.9.jar) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['Mario'/173, l='Prova', x=507,82, y=88,00, z=13,88]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by pauljoda** [comment]
We have found the issue. We are working on it. Thanks for the report

**Comment by mario-88ce** [comment]
Please , Thank you for your patience

**Comment by pauljoda** [comment]
I'm going to open it so we can tag the commit that fixed it
