### ISSUE TITLE
Breaking piping with pickaxe causes crash

### ISSUE THREAD

**Issue by ewanm89** [TeamBR-Modding/NeoTech#234]
What Version of NeoTech are you using: 
NeoTech-1.8.9-2.4.1.jar
forge-1.8.9-11.15.1.1764.jar
Bookshelf-API-1.8.9-2.3.6.jar

Breaking neotech pipes with a pickaxe causes the following crash (this was with a silk touch  neotech electric pickaxe, however is repeatable with tinkers construct pickaxe too). Picking up via wrench works fine.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 19/03/16 19:51
Description: Rendering Block Entity

java.lang.ArrayIndexOutOfBoundsException: 16
    at net.minecraftforge.client.model.pipeline.LightUtil.pack(LightUtil.java:230)
    at net.minecraftforge.client.model.pipeline.WorldRendererConsumer.put(WorldRendererConsumer.java:39)
    at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:109)
    at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:10)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:120)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.access$200(MultipartContainerSpecialRenderer.java:30)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileCoverableSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:181)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileCoverableSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:153)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:720)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1390)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraftforge.client.model.pipeline.LightUtil.pack(LightUtil.java:230)
    at net.minecraftforge.client.model.pipeline.WorldRendererConsumer.put(WorldRendererConsumer.java:39)
    at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:109)
    at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:10)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:120)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.access$200(MultipartContainerSpecialRenderer.java:30)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileCoverableSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:181)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileCoverableSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:153)

-- Block Entity Details --
Details:
    Name: pipeItemBasicInterface // com.dyonovan.neotech.pipes.tiles.item.ItemInterfacePipe
    Block type: ID #1186 (tile.neotech:pipeItemBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-338,64,67), Chunk: (at 14,4,3 in -22,4; contains blocks -352,0,64 to -337,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #1186 (tile.neotech:pipeItemBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:136)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:114)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:720)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1390)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['ewanm89'/4030, l='MpServer', x=-336.07, y=64.00, z=67.26]]
    Chunk stats: MultiplayerChunkCache: 1089, 1089
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -132.00,64.00,256.00 - World: (-132,64,256), Chunk: (at 12,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 4280324 game time, 4460610 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 67 total; [EntityPlayerSP['ewanm89'/4030, l='MpServer', x=-336.07, y=64.00, z=67.26], EntityAuraNode['Aura Node'/4231, l='MpServer', x=-213.50, y=63.50, z=3.50], EntityAuraNode['Aura Node'/4234, l='MpServer', x=-196.50, y=70.50, z=22.50], EntityAuraNode['Aura Node'/4238, l='MpServer', x=-438.50, y=63.50, z=-73.50], EntityAuraNode['Aura Node'/4117, l='MpServer', x=-443.50, y=17.50, z=103.50], EntityAuraNode['Aura Node'/3861, l='MpServer', x=-227.50, y=29.50, z=126.50], EntityAuraNode['Aura Node'/3863, l='MpServer', x=-224.50, y=82.50, z=146.50], EntitySoul['Soul'/3996, l='MpServer', x=-352.72, y=63.00, z=47.34], EntitySheep['Sheep'/3997, l='MpServer', x=-363.09, y=63.00, z=47.06], EntitySheep['Sheep'/3998, l='MpServer', x=-367.84, y=63.00, z=47.06], EntitySheep['Sheep'/3999, l='MpServer', x=-366.63, y=63.00, z=47.06], EntitySheep['Sheep'/4000, l='MpServer', x=-364.25, y=63.00, z=47.06], EntitySheep['Sheep'/4001, l='MpServer', x=-365.44, y=63.00, z=47.06], EntitySquid['Squid'/4002, l='MpServer', x=-328.15, y=59.87, z=38.22], EntitySheep['Sheep'/4003, l='MpServer', x=-365.69, y=63.00, z=48.44], EntitySheep['Sheep'/4004, l='MpServer', x=-363.09, y=63.00, z=48.16], EntityBat['Bat'/4132, l='MpServer', x=-413.83, y=16.08, z=-10.36], EntitySheep['Sheep'/4005, l='MpServer', x=-367.53, y=63.00, z=48.66], EntitySheep['Sheep'/4006, l='MpServer', x=-364.31, y=63.00, z=48.63], EntitySheep['Sheep'/4007, l='MpServer', x=-363.09, y=63.00, z=49.91], EntitySheep['Sheep'/4008, l='MpServer', x=-364.31, y=63.00, z=49.91], EntitySheep['Sheep'/4009, l='MpServer', x=-367.59, y=63.00, z=49.91], EntitySquid['Squid'/4010, l='MpServer', x=-335.53, y=59.94, z=7.34], EntitySquid['Squid'/4012, l='MpServer', x=-349.56, y=58.75, z=9.72], EntitySheep['Sheep'/4013, l='MpServer', x=-368.94, y=63.00, z=47.06], EntitySkeleton['Skeleton'/4014, l='MpServer', x=-360.72, y=5.00, z=2.78], EntitySquid['Squid'/4015, l='MpServer', x=-352.00, y=55.78, z=8.84], EntitySquid['Squid'/4017, l='MpServer', x=-324.28, y=53.78, z=19.34], EntitySquid['Squid'/4031, l='MpServer', x=-313.53, y=60.44, z=37.13], EntityBat['Bat'/4032, l='MpServer', x=-350.59, y=12.10, z=116.69], EntityBat['Bat'/4033, l='MpServer', x=-350.25, y=12.10, z=116.75], EntityBat['Bat'/4034, l='MpServer', x=-350.28, y=11.93, z=116.31], EntityZombie['Zombie'/4035, l='MpServer', x=-396.31, y=11.48, z=106.53], EntityBat['Bat'/4036, l='MpServer', x=-396.26, y=18.34, z=100.77], EntitySkeleton['Skeleton'/4037, l='MpServer', x=-388.34, y=24.00, z=42.60], EntityCreeper['Creeper'/4038, l='MpServer', x=-385.50, y=24.00, z=41.50], EntityAuraNode['Aura Node'/4039, l='MpServer', x=-403.50, y=70.50, z=89.50], EntitySheep['Sheep'/3783, l='MpServer', x=-368.94, y=63.00, z=48.19], EntityChicken['Chicken'/4040, l='MpServer', x=-409.50, y=66.00, z=49.63], EntitySheep['Sheep'/3784, l='MpServer', x=-368.94, y=63.00, z=49.50], EntityCreeper['Creeper'/4041, l='MpServer', x=-371.50, y=63.00, z=140.50], EntityChicken['Chicken'/3785, l='MpServer', x=-324.25, y=62.50, z=119.22], EntityCreeper['Creeper'/4042, l='MpServer', x=-379.39, y=29.76, z=16.65], EntitySkeleton['Skeleton'/4043, l='MpServer', x=-380.50, y=38.00, z=1.50], EntitySquid['Squid'/4046, l='MpServer', x=-388.34, y=49.16, z=2.69], EntityChicken['Chicken'/3793, l='MpServer', x=-315.56, y=66.00, z=127.59], EntitySquid['Squid'/4050, l='MpServer', x=-306.88, y=50.50, z=8.09], EntityItem['item.item.egg'/3794, l='MpServer', x=-315.75, y=65.00, z=126.84], EntityAuraNode['Aura Node'/4051, l='MpServer', x=-358.50, y=65.50, z=157.50], EntityZombie['Zombie'/3795, l='MpServer', x=-317.50, y=37.00, z=138.50], EntitySkeleton['Skeleton'/3796, l='MpServer', x=-315.16, y=69.00, z=143.22], EntityChicken['Chicken'/4061, l='MpServer', x=-416.50, y=62.59, z=36.41], EntityZombie['Zombie'/4062, l='MpServer', x=-305.50, y=15.00, z=-0.50], EntityCreeper['Creeper'/3806, l='MpServer', x=-293.06, y=66.00, z=124.47], EntityCreeper['Creeper'/4063, l='MpServer', x=-309.50, y=15.00, z=-3.50], EntityZombie['Zombie'/3807, l='MpServer', x=-303.50, y=35.00, z=130.50], EntitySkeleton['Skeleton'/3808, l='MpServer', x=-303.56, y=37.00, z=126.81], EntityBat['Bat'/3809, l='MpServer', x=-302.78, y=36.19, z=128.69], EntityCreeper['Creeper'/4069, l='MpServer', x=-272.50, y=20.00, z=11.94], EntityBat['Bat'/4071, l='MpServer', x=-387.06, y=21.20, z=147.28], EntityCreeper['Creeper'/4074, l='MpServer', x=-392.09, y=5.00, z=-3.66], EntityZombie['Zombie'/4075, l='MpServer', x=-293.50, y=31.00, z=-9.50], EntitySkeleton['Skeleton'/3820, l='MpServer', x=-278.50, y=27.00, z=77.50], EntitySpider['Spider'/3821, l='MpServer', x=-284.50, y=69.00, z=129.50], EntityAuraNode['Aura Node'/3822, l='MpServer', x=-282.50, y=78.50, z=157.50], EntitySpider['Spider'/3832, l='MpServer', x=-268.56, y=68.00, z=122.81], EntityZombie['Zombie'/3833, l='MpServer', x=-265.50, y=67.00, z=122.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1280036808 bytes (1220 MB) / 2882535424 bytes (2749 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 86 mods loaded, 86 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   CoreXU2{1} [CoreXU2] (minecraft.jar) 
    UCHIJAAAA   bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies] (BetterThanBunnies-1.8.9-1.0.1.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.1.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
    UCHIJAAAA   JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
    UCHIJAAAA   bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0} [BuildCraft] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0} [BC Builders] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0} [BC Transport] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0} [BC Energy] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0} [BC Silicon] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0} [BC Robotics] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0} [BC Factory] (buildcraft-7.2.0.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.2.0} [BuildCraft Compat] (buildcraft-compat-7.2.0.jar) 
    UCHIJAAAA   buildingbrickscompatvanilla{1.8.9-1.4.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.4.2.jar) 
    UCHIJAAAA   buildingbricks{1.8.9-1.4.2} [Building Bricks] (BuildingBricks-1.8.9-1.4.2.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAA   CharsetLib{0.2.1} [â€½] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetTweaks{0.2.1} [*] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetWires{0.2.1} [+] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetAudio{0.2.1} [â™«] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetStorage{0.2.1} [#] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetPipes{0.2.1} [|] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   CharsetGates{0.2.1} [&] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
    UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
    UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
    UCHIJAAAA   craftingtweaks{3.0.52} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.52.jar) 
    UCHIJAAAA   crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-1.8.8-3.0.2.jar) 
    UCHIJAAAA   CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
    UCHIJAAAA   ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
    UCHIJAAAA   deepresonance{1.1.4beta17} [DeepResonance] (deepresonance-1.8.9-1.1.4beta17.jar) 
    UCHIJAAAA   dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar) 
    UCHIJAAAA   ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
    UCHIJAAAA   EnderTanks{1.2.1} [EnderTanks] (EnderTanks-1.8.9-1.2.1.jar) 
    UCHIJAAAA   ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
    UCHIJAAAA   forgeanalytics{0.0.0.13} [Forge Analytics] (ForgeAnalytics-1.8.9-0.0.0.15.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   furnus{1.73} [Furnus] (Furnus-1.8.9-1.73.jar) 
    UCHIJAAAA   graves{1.8.9-b46-universal} [Graves Mod] (graves-1.8.9-b46-universal.jar) 
    UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
    UCHIJAAAA   HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
    UCHIJAAAA   IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
    UCHIJAAAA   llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
    UCHIJAAAA   mantle{1.8.9-0.9.1.jenkins99} [Mantle] (Mantle-1.8.9-0.9.1.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   ModLister{1.8.9-1.0.7} [ModLister] (ModLister-1.8.9-1.0.7.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
    UCHIJAAAA   MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0b.jar) 
    UCHIJAAAA   neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAA   notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
    UCHIJAAAA   progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAA   Psi{beta-23} [Psi] (Psi-beta-23.jar) 
    UCHIJAAAA   randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
    UCHIJAAAA   ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAAAA   rftools{4.23beta33} [RFTools] (rftools-1.8.9-4.23beta33.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
    UCHIJAAAA   thaumicinfusion{4.83} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.83.jar) 
    UCHIJAAAA   wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
    UCHIJAAAA   denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.0.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.1.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 980/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

    Launched Version: forge-11.15.1.1764
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
```

**Comment by pauljoda** [comment]
This seems to be an issue with MCMultiPart. We will watch it as updates occur

**Comment by pauljoda** [comment]
Pipes and multipart are no longer part of neotech, closing
