### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#252]
What Version of NeoTech are you using:
3.0.0 for minecraft 1.9
If possible, did you break and replace the block:
no
[http://pastebin.com/5k773StY](http://pastebin.com/5k773StY)

**Comment by pauljoda** [comment]
Link doesn't work

**Comment by ArMoReDfUrY** [comment]
i'm getting a crash at startup too.

Edit: 1.9 Forge 12.16.0.1811 and using NeoTech-1.9-3.0.0-B31 & Bookshelf-API-1.9-3.0.0-B23

[crash-2016-03-28_12.21.39-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/191281/crash-2016-03-28_12.21.39-client.txt)

Love the mod, thanks for the fun times. :+1:

**Comment by pauljoda** [comment]
Yeah, forge updated yet again and broke everything. We will get on this as soon as possible

**Comment by tiarnia** [comment]
great news its hard to keep up i know

**Comment by tiarnia** [comment]
fixed link but i think you see the forge issue

**Comment by Dyonovan** [comment]
Releasing new version as we speak updated to Forge 1811

**Comment by ArMoReDfUrY** [comment]
still got a crash on boot. same issue :'(

tested on Forge 1.9  1811 & 1813

Time: 3/30/16 1:40 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.dyonovan.neotech.registries.AbstractRecipeHandler.getItemStackString(AbstractRecipeHandler.scala:225)
	at com.dyonovan.neotech.registries.CrucibleRecipeHandler.addCrucibleRecipe(CrucibleRecipeHandler.scala:142)
	at com.dyonovan.neotech.registries.CrucibleRecipeHandler.generateDefaultRecipes(CrucibleRecipeHandler.scala:94)
	at com.dyonovan.neotech.registries.AbstractRecipeHandler.loadHandler(AbstractRecipeHandler.scala:82)
	at com.dyonovan.neotech.managers.RecipeManager$.init(RecipeManager.scala:34)
	at com.dyonovan.neotech.NeoTech$.init(NeoTech.scala:93)
	at com.dyonovan.neotech.NeoTech.init(NeoTech.scala)
