### ISSUE TITLE
Crash at startup with Forge 1811

### ISSUE THREAD

**Issue by kwpugh** [TeamBR-Modding/NeoTech#256]
FOR 1.9 VERSION: IF YOU HAVE THIS CRASH IT IS FORGE, DON'T POST: 
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/TRSRTransformation

What Version of NeoTech are you using: 
- Bookshelf-API-1.9-3.0.1.jar
- NeoTech-1.9-3.0.1.jar

If possible, did you break and replace the block: crash at startup

Please Pastebin.com the crash Report and put link here:  http://pastebin.com/raw/kjE8cp3e

**Comment by ArMoReDfUrY** [comment]
still got a crash on boot. same issue :'(

tested on Forge 1.9 1811 & 1813

Time: 3/30/16 1:40 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 1
at com.dyonovan.neotech.registries.AbstractRecipeHandler.getItemStackString(AbstractRecipeHandler.scala:225)
at com.dyonovan.neotech.registries.CrucibleRecipeHandler.addCrucibleRecipe(CrucibleRecipeHandler.scala:142)
at com.dyonovan.neotech.registries.CrucibleRecipeHandler.generateDefaultRecipes(CrucibleRecipeHandler.scala:94)
at com.dyonovan.neotech.registries.AbstractRecipeHandler.loadHandler(AbstractRecipeHandler.scala:82)
at com.dyonovan.neotech.managers.RecipeManager$.init(RecipeManager.scala:34)
at com.dyonovan.neotech.NeoTech$.init(NeoTech.scala:93)
at com.dyonovan.neotech.NeoTech.init(NeoTech.scala)

**Comment by Dyonovan** [comment]
Pushing new version to fix. 3.0.2 Give it 5 mins to be approved on curse

**Comment by kwpugh** [comment]
Still use v3.0.1 of Bookshelf?

**Comment by kwpugh** [comment]
Ok, I added Bookshelf and the new Neotecj 3.0.2 and I get this:   http://pastebin.com/raw/y2Dm7Zyt
