### ISSUE TITLE
Tried to put a full stack of silver ore into the crusher

### ISSUE THREAD

**Issue by MoonCutter2B** [TeamBR-Modding/NeoTech#386]
What Version of NeoTech are you using:1.10.2-3.3.0

Please Pastebin.com the crash Report and put link here:

java.lang.NullPointerException: Updating screen events
    at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:244)
    at com.teambrmodding.neotech.registries.CrusherRecipes$$anonfun$getOutput$1.apply(CrusherRecipeHandler.scala:217)
    at com.teambrmodding.neotech.registries.CrusherRecipes$$anonfun$getOutput$1.apply(CrusherRecipeHandler.scala:201)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at com.teambrmodding.neotech.registries.CrusherRecipes.getOutput(CrusherRecipeHandler.scala:201)
    at com.teambrmodding.neotech.registries.CrusherRecipes.getOutput(CrusherRecipeHandler.scala:189)
...

**Comment by MoonCutter2B** [comment]
So far it hasn't happened if I add a stack that isn't full.

**Comment by ChilledDayz** [comment]
NeoTech-1.10.2-3.3.0

[http://pastebin.com/a82Wi8kf]

crash placing any ore into the electric crusher. I've tried different ores and amounts, but it still crashes.

**Comment by pauljoda** [comment]
Try letting the configs re generate. Delete the configs in the config directory and let me know if the issue still persists

**Comment by ChilledDayz** [comment]
I can confirm that deleting the configs fixes the problem. Dyonovan did suggest this in his stream I just wasn't able to test at the time. Thank guys
