### ISSUE TITLE
NeoTech 1.8.0-2.3.3 Crash

### ISSUE THREAD

**Issue by CrazyCodeUK** [TeamBR-Modding/NeoTech#76]
With bookshelf 1.8.9-2.2.8

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: rock
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: rock
    at com.dyonovan.neotech.common.blocks.machines.BlockGrinder.<init>(BlockGrinder.scala:30)
    at com.dyonovan.neotech.managers.BlockManager$.<init>(BlockManager.scala:39)
    at com.dyonovan.neotech.managers.BlockManager$.<clinit>(BlockManager.scala)
    at com.dyonovan.neotech.NeoTech$.preInit(NeoTech.scala:60)
    at com.dyonovan.neotech.NeoTech.preInit(NeoTech.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)

**Comment by Dyonovan** [comment]
Which version are you using? The -dev version or the normal version. The dev version is only for Development environments.

**Comment by CrazyCodeUK** [comment]
NeoTech-1.8.9-2.3.3.jar listed as a "release" version on curse

**Comment by Dyonovan** [comment]
Hmm wierd. Can I get a full pastebin.com of the crash log

**Comment by CrazyCodeUK** [comment]
Of course. Let me know if there is anything else you need.

http://pastebin.com/tr4LMjH7

**Comment by Dyonovan** [comment]
`UCE neotech{2.3.3} [NeoTech] (NeoTech-1.8.9-2.3.3-dev.jar) 
`
Your using the dev jar. You need to use the normal jar. Here is the link http://minecraft.curseforge.com/projects/neotech/files/2280422/download

Both jar's are available on curse. Just make sure you use the one that doesnt have -dev in i

**Comment by CrazyCodeUK** [comment]
It and was was curse "release" link (http://www.curse.com/mc-mods/minecraft/228643-neotech/2280422) was the location of downlaod used

**Comment by Dyonovan** [comment]
For some reason, curse approved the dev version seconds before the normal version. You might have gotten lucky and for those few seconds something screwed up. 

Try with the new one and let me know if it works
